name: Run API Tests and Deploy Allure Report

on:
  push:
    branches:
      - main

jobs:
  test_api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Set up Maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Run API tests
        run: mvn clean test

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports
          path: target/surefire-reports/*.xml

  generate_report:
    runs-on: ubuntu-latest
    needs: test_api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Download test reports
        uses: actions/download-artifact@v4
        with:
          name: junit-reports
          path: target/surefire-reports

      - name: Generate Allure report
        run: mvn allure:report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/allure-maven-plugin
          branch: main
