name: Run Tests and Deploy Allure Report

on:
  push:
    branches: ["main"]  # Roda quando há push na branch main
  workflow_dispatch:  # Permite rodar manualmente

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Install Allure
        run: |
          sudo apt-add-repository universe -y
          sudo apt update
          sudo apt install -y allure

      - name: Run API tests with Maven
        run: mvn clean test

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Allure Report Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './target/site/allure-results'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
